@startuml
autonumber

title Changing SAML Connection from an existing to a new Custom Domain

actor User as u
participant "Application\n(app.example.com)" as app
participant "New SP domain\n(new.example.com)" as a0
participant "Existing SP Domain\n(old.example.com)" as sp
participant "SAML IdP\n(login.idp.com)" as idp

u -> app: access

app -> a0: Request session with upstream idp
a0 -> idp: POST/GET \n { SAMLRequest & RelayState }
idp -> u: authenticate
u --> idp: credentials

idp -> sp: POST /login/callback \n { SAMLResponse & RelayState }
sp -> sp: Detect SAML response \n {method=POST & SAMLResponse in body}
sp -> a0: 308 Redirect \n Location: new.example.com

a0 -> a0: validate & establish session
a0 -> app: authenticated

app -> u: data
@enduml